name: E2E Test
on:
    push:
      branches:
      - main
    pull_request:
    workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: slack_server_mock
        tags: latest
        containerfiles: |
          ./Containerfile

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt

    - name: Run tests
      run: |
        pytest test
